/**
 * Background presets for the flat-lay composer.
 *
 * Each preset bundles a real procedural texture PNG (generated by
 * `scripts/generate-flat-lay-textures.py`) PLUS a fallback solid color used
 * for placeholders or while the texture loads.
 *
 * Light backgrounds get warmer / softer shadows; dark backgrounds get pitch-
 * black shadows. Watermark color flips polarity for readability.
 */

import type { ImageSourcePropType } from 'react-native';

export type FlatLayBackground = {
  id: string;
  name: string;
  /** Fallback solid fill color (matches the texture's average tone). */
  color: string;
  /** Real texture image (procedural PNG/JPG in assets/flat-lay/). */
  texture: ImageSourcePropType;
  /** Color used for item drop shadows on this background. */
  shadowColor: string;
  /** Color for the "via Maderobe" watermark text on this background. */
  watermarkColor: string;
};

export const FLAT_LAY_BACKGROUNDS: FlatLayBackground[] = [
  {
    id: 'dark-wood',
    name: 'Bois foncé',
    color: '#4A321E',
    texture: require('../assets/flat-lay/dark-wood.jpg'),
    shadowColor: '#000000',
    watermarkColor: 'rgba(255,255,255,0.55)',
  },
  {
    id: 'light-wood',
    name: 'Bois clair',
    color: '#C8A678',
    texture: require('../assets/flat-lay/light-wood.jpg'),
    shadowColor: '#4A2F0E',
    watermarkColor: 'rgba(0,0,0,0.45)',
  },
  {
    id: 'marble',
    name: 'Marbre',
    color: '#F4F1EC',
    texture: require('../assets/flat-lay/marble.jpg'),
    shadowColor: '#7C7669',
    watermarkColor: 'rgba(0,0,0,0.45)',
  },
  {
    id: 'linen',
    name: 'Lin',
    color: '#D9C9B0',
    texture: require('../assets/flat-lay/linen.jpg'),
    shadowColor: '#6E5A39',
    watermarkColor: 'rgba(0,0,0,0.50)',
  },
  {
    id: 'charcoal',
    name: 'Ardoise',
    color: '#1F2125',
    texture: require('../assets/flat-lay/charcoal.jpg'),
    shadowColor: '#000000',
    watermarkColor: 'rgba(255,255,255,0.45)',
  },
];

export const DEFAULT_FLAT_LAY_BACKGROUND = FLAT_LAY_BACKGROUNDS[0];

export function getBackgroundById(id: string | undefined): FlatLayBackground {
  if (!id) return DEFAULT_FLAT_LAY_BACKGROUND;
  return FLAT_LAY_BACKGROUNDS.find((b) => b.id === id) ?? DEFAULT_FLAT_LAY_BACKGROUND;
}
